services:
  postgres:
    image: ${POSTGRES_APP}
    container_name: ${POST_HOST}
    environment:
      - POST_DB=${POSTGRES_DB}
      - POST_USER=${POSTGRES_USER}
      - POST_PASSWORD=${POSTGRES_PASSWORD}
      - NODE=${NODE_ENV}
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/postgres_data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PG_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PG_PASS=${PGADMIN_DEFAULT_PASSWORD}
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
             
  #my_db:
    #image: mysql:8
    #environment:
     # - MYSQL_ROOT_USER=root
      #- MYSQL_ROOT_PASSWORD=root
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
      #- MYSQL_DATABASE=${MYSQL_DB_NAME}
      #- MY_USER=${MYSQL_USER}
    #env_file: .env
    #ports:
     # - "3307:3306"
    #volumes:
     # - ./db_data:/var/lib/mysql/data

  #phpmyadmin:
    #image: phpmyadmin/phpmyadmin
    #depends_on:
     # - my_db
    #environment:
     # - PMA_HOST=my_db
      #- PMA_PORT=3307
    #restart: always
    #ports:
     # - "8080:80"

volumes:
  db-volume:
    name: pg-data