services:
  postgres:
    image: ${POSTGRES_APP}
    container_name: ${POST_HOST}
    environment:
      - POST_DB=${POSTGRES_DB}
      - POST_USER=${POSTGRES_USER}
      - POST_PASSWORD=${POSTGRES_PASSWORD}
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PG_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PG_PASS=${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "5050:80"
    depends_on:
      - postgres
      
       
volumes:
  db-volume:
    name: pg-data

 